### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by dfault-user** [NonameVM/NonameVM-Server#1]
Good morning,

As it currently concerns, [this repository](https://github.com/NonameVM/NonameVM-Server) is currently in violation of the GNU General Public License, Version 3 license terms. Specifically, the terms listed under "Conveying Modified Source Versions". You did not make this software, but rather hard forked it from [Computernewb's original CollabVM-Server TypeScript rewrite](https://github.com/computernewb/collabvm-1.2.ts), with poorly renamed assets and entirely missing source code that would make this 'version' of the server functional. The license for this server, derived from CollabVM-Server TypeScript, is missing.

Best regards

**Comment by NonameVM** [comment]
We will fix it soon , only compiled files will be here.

**Comment by dfault-user** [comment]
Closed as stale
